// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4a73bc7c-ef74-46d1-893b-fcb7532d7c40";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


String gemini_recomendaciones;
float DS18b20_temperatura;
float Ph22_pchimetro;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gemini_recomendaciones, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(DS18b20_temperatura, READ, ON_CHANGE, NULL, 2);
  ArduinoCloud.addProperty(Ph22_pchimetro, READ, ON_CHANGE, NULL, 2);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
